### ISSUE TITLE
Server shutdown in 30 minutes

### ISSUE THREAD

**Issue by sense-design** [monday-consulting/firstspirit-docker#1]
Building the image works fine but after the server started I receive the message that the FirstSpirit server will shutdown in 30 minutes.

1. What license from Crownpeak is required to keep the server running?
2. Is a localhost developer license enough because my developer server (ip based) is not working?
3. Would this be something for the README?

**Comment by cr4igo** [comment]
1. Normal Partner-Developer License. Take care that you are only allowed to do non-customer specific stuff with this Partner-Developer License. So for example when you develop a FirstSpirit Module and want to test this on your "local" machine.
Also keep in mind, that with the "30 Minutes license" you dont have the ACCESS_API licensed, so e.g. no fs-cli would work!

2. You need to have a license, that is not bound to a specific IP! In docker/k8s etc. you dont use IP-Addresses, as they are randomly generated and subjected to change, also as best practise.

3. Yes, we could add this to the readme. Also maybe how to exchange the license, because this is a reoccuring task :)
